### ISSUE TITLE
Updates to Docker build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#108]
Several changes are needed to the docker build now that we are doing in the same repo
1. Switch to node 10 (not 14 -- which is failing to work properly)
2. Avoid re-cloning the source and building from scratch, which was previously needed as the dockerfile was in the egeria repo

**Comment by planetf1** [comment]
I have considered the current build process and propose another change

The prior approach was based on a self-building image where, when we built the container, we extracted from git and built locally.
This was because we were running the docker build in a different repo/pipeline to the UI node build.

Now that the docker file and code are co-located, there is no need to build twice.

Instead we can simply copy the output files across into the container.

See

**Comment by sarbull** [comment]
@planetf1  can we close this?

**Comment by planetf1** [comment]
Yes
