### ISSUE TITLE
Egeria UI broken 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#110]
The Egeria UI currently does not work in our Helm Charts using the existing zuul based redirection

When the UI is accessed (via the ui server chassis) I see 'Egeria UI' as the title / favicon but the content area is blank, and the javascript console in chrome reports

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "paper-menu-grow-height-animation" has already been used with this registry
    at Polymer (https://c12bb70b-eu-gb.lb.appdomain.cloud/src/my-app.js:5867:139)
    at https://c12bb70b-eu-gb.lb.appdomain.cloud/src/my-app.js:14878:66
DevTools failed to load SourceMap: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://eoolfmmapnkhandljfaaofncecfakljd/dist/Versioning.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

See https://github.com/odpi/egeria/pull/4926 where I am making the change to implement an nginx proxy to support https://github.com/odpi/egeria/issues/4549

The docker image is posted to https://hub.docker.com/repository/docker/odpi/egeria-ui 

The UI was working correctly as of the 2.7 release, so this looks like a recent regression

**Comment by sarbull** [comment]
@planetf1 in the readme file is states that it works with NodeJS 10.13.0 LTS, can you try using that version?

**Comment by planetf1** [comment]
In #111 I refactored the docker build. Now it only gets built once, with node 10.  However the end result is the same - UI not working at all. Same issue.

**Comment by sarbull** [comment]
@planetf1 can you add in the build phase node -v and npm -v

**Comment by lpalashevski** [comment]
@planetf1, the latest docker image works well -- we tested the image with local docker setup. Now with the latest pipeline configuration in place we have more stable build. 

Please note that now the name of the image is changed to egeria-ui (was egeria-uistatic). Can we update the name in the helm vars and try to deploy again?

**Comment by planetf1** [comment]
Thanks for noticing the error in the image names not aligning!

**Comment by planetf1** [comment]
Closing - user error in using wrong docker image ..
