### ISSUE TITLE
Appropriate UI release for base egeria release 2.9 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#142]
Egeria has now branched for 2.9 - see https://github.com/odpi/egeria/issues/5075. 

If you would like a new version of the egeria-ui included by the helm/compose charts in egeria 2.9, please can you create a 2.9 release. Then a PR will need doing for the egeria-2.9 release on base egeria, but this code is under test and will be released soon (days)

For now I will set the egeria code to use the 2.8 version, which is the last 'release'.

**Comment by sarbull** [comment]
hi, i will bump the version to 2.9.0 for egeria-ui after the egeria-2.9 comes out, following the same strategy

**Comment by planetf1** [comment]
2.9 egeria has already shipped. The charts are using the 2.8 UI release.
