### ISSUE TITLE
Migrate build of container to egeria-ui project

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#18]
Currently the container image for the static content is built under the main egeria project as part of the maven merge build running under azure pipelines

I propose we move the container build here, so that it is consistent with the code it contains. 
 - Look at if we can do this under github actions
 - will need access to the odpi credentials for accessing the repo
 - we could initially push to the github container repo for testing
 - we could look at whether even a PR could build the container (for verification and testing) - and use a PR specific 'tag'

There is still code in egeria repo that references the image - docker compose & lab helm chart. If the name of the image, location, or version changes, this will need updating. 
Two changes we've not done yet in egeria for this image
 - verifying image security. 
 - Using a UBI image (we do use the redhat UBI-8 image for base egeria, hopefully can use the same for the UI)
 - ensure we always use https

**Comment by sarbull** [comment]
@planetf1 can this be closed?

**Comment by sarbull** [comment]
i updated the README file to align the fully decoupling of the UI from the Backend, we can start with HTTPS with `polymer` if needed, i managed to start it with a custom certificate

**Comment by planetf1** [comment]
yes this can be closed now.
