### ISSUE TITLE
Migrate docker build to this repo & all builds to github actions

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#47]
Followup to #2 
In base egeria our PR builds have moved to github actions which are very promising.
Opening this up to track consideration of same for egeria-ui repo

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/issues/4664

- Move build to github actions
- consider what (if any) artifacts should be published, and if so where to. This could be an npm package, or simply an archive of some kind. This should be uploaded by the action

**Comment by planetf1** [comment]
Recommend we do this as part of the refactoring of the chassis/static UI

**Comment by planetf1** [comment]
I would like to move the docker build of egeria-ui over into this repo.
This will make it much clear what this repo is providing, and how versions etc are managed. 

We'll have a docker image, it will be posted to dockerhub as part of the merge build
I'll look at moving the builds over to github actions, as we've done with other repos, which should be simple. They can be added as optional steps until working

I'll look at then updating the helm definitions etc to support the use of the UI with a proxy definition. These remain in the base for now but are expected to move to a samples repo at a future date.

**Comment by sarbull** [comment]
@planetf1 how can i help?

**Comment by planetf1** [comment]
The first stage of this is done - ie a 'simple' migration. 
I will disable the azure build, and the docker build in the base 

Note that this build is inefficient currently as it rebuilds within the container, but its a first step..

**Comment by planetf1** [comment]
Images pushed correctly to dockerhub: https://hub.docker.com/repository/registry-1.docker.io/odpi/egeria-ui/tags?page=1&ordering=last_updated

**Comment by planetf1** [comment]
completed
