### ISSUE TITLE
'About' does not work

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-ui#573]
Navigating to 'about' via
 a) (i) icon at bottom left
 b) 'About' on top navigation bar
 
 results in a page not loading
 
 Additionally, there is no way out - except back. No timeout is observed if a remote request is being issued.
 
 
<img width="1891" alt="Screenshot 2023-03-29 at 12 17 43" src="https://user-images.githubusercontent.com/7292002/228518771-30076dcb-e799-433b-97d0-22093684031c.png">

original report: https://github.com/odpi/egeria-ui/issues/480

**Comment by sarbull** [comment]
@planetf1 it would be better if you can add the developer tools in the print screen to get a better understanding of what is happening(interested in the network response and console output of developer tools)
